#!/usr/bin/env ansible-playbook
---

   - name: "Ensure directory structure for docker ({{item_app}})"
     file:
       path: '{{docker_files_path}}/{{item_app}}/{{item.path}}/'
       state: directory
       mode: '{{item.mode}}'
       force: no
       recurse: yes
     with_filetree: "templates/docker/{{item_app}}/"
     when: item.state == 'directory'
     ignore_errors: yes
     no_log: true

   - name: "Copy Docker files ({{item_app}})"
     template:
       src: '{{item.src}}'
       dest: '{{docker_files_path}}/{{item_app}}/{{item.path}}'
       force: yes
       mode: '{{item.mode}}'
       group: '{{item.group}}'
       owner: '{{item.owner}}'
     with_filetree: "templates/docker/{{item_app}}/"
     when: item.state == 'file' #and (item.src | basename) != '.gitignore'
     ignore_errors: yes
     no_log: true

...