#!/usr/bin/env ansible-playbook
---

- name: Config docker env
  hosts: application
  tasks:
   - name: Creates directory for docker
     file:
       path: '{{docker_files_path}}'
       state: directory
       recurse: yes

   - name: Ensure directory structure for docker
     file:
       path: '{{docker_files_path}}/{{item.path}}'
       state: directory
       mode: '{{item.mode}}'
       force: no
       recurse: yes
     with_filetree: templates/docker/
     when: item.state == 'directory'
     ignore_errors: yes
     no_log: true

   - name: Copy Docker files
     template:
       src: '{{item.src}}'
       dest: '{{docker_files_path}}/{{item.path}}'
       force: yes
       mode: '{{item.mode}}'
       group: '{{item.group}}'
       owner: '{{item.owner}}'
     with_filetree: templates/docker/
     when: item.state == 'file' and (item.src | basename) != '.gitignore'
     ignore_errors: yes
     no_log: true

   - name: Fix mongodb key permissions
     become: yes
     file:
       path: '{{docker_files_path}}/mongodb/config/keyfile'
       mode: '0400'
       owner: '999'
       group: '999'

   - name: Fix mongodb data folder permissions
     become: yes
     file:
       path: '{{item}}'
       owner: '999'
       group: '999'
     with_items:
      - '{{docker_files_path}}/mongodb/data/log'
      - '{{docker_files_path}}/mongodb/data/home'

   - name: "Add alias for PHP-CLI"
     lineinfile:
       path: ~/.bashrc
       line: "alias php='{{docker_files_path}}/php-cli/cli.sh'"

   - name: "Add alias for Composer"
     lineinfile:
       path: ~/.bashrc
       line: "alias composer='{{docker_files_path}}/php-cli/composer.sh'"

...