#!/usr/bin/env ansible-playbook
---

- name: Config docker env
  hosts: application
  gather_facts: no
  strategy: free
  tasks:
   - name: Creates directory for docker
     file:
       path: '{{docker_files_path}}'
       state: directory
       recurse: yes

   - name: Copy docker pull and network files
     template:
       src: 'templates/docker/{{item}}'
       dest: '{{docker_files_path}}/{{item}}'
       mode: 'u=rwx,g=r,o=r'
       force: yes
     with_items: 
        - pull.sh
        - network.sh
        - prune.sh
     no_log: true

   - name: Ensure directory structure for docker
     include_tasks: _inner_docker.yml
     loop: "{{available_applications}}"
     loop_control:
       loop_var: item_app
     no_log: true


   #- name: Ensure directory structure for docker
   #  file:
   #    path: '{{docker_files_path}}/{{item.path}}'
   #    state: directory
   #    mode: '{{item.mode}}'
   #    force: no
   #    recurse: yes
   #  with_filetree: "templates/docker/"
   #  when: item.state == 'directory'
   #  ignore_errors: yes
   #  no_log: true

   #- name: Copy Docker files
   #  template:
   #    src: '{{item.src}}'
   #    dest: '{{docker_files_path}}/{{item.path}}'
   #    force: yes
   #    mode: '{{item.mode}}'
   #    group: '{{item.group}}'
   #    owner: '{{item.owner}}'
   #  with_filetree: "templates/docker/"
   #  when: item.state == 'file' and (item.src | basename) != '.gitignore'
   #  ignore_errors: yes
   #  no_log: true

   - name: Fix mongodb key permissions
     become: yes
     file:
       path: '{{docker_files_path}}/mongodb/config/keyfile'
       mode: '0400'
       owner: '999'
       group: '999'
     ignore_errors: yes
     when: "docker_mongodb_image is defined"

   - name: Fix container folders permissions
     become: yes
     file:
       path: '{{item}}'
       owner: '999'
       group: '999'
     with_items:
      - '{{docker_files_path}}/mongodb/data/log'
      - '{{docker_files_path}}/mongodb/data/home'
     when: "docker_mongodb_image is defined"
      #- '{{docker_files_path}}/rabbitmq/data/log'
      #- '{{docker_files_path}}/rabbitmq/data/lib'
      #- '{{docker_files_path}}/nginx/runtime/logs'
      #- '{{docker_files_path}}/nginx/runtime/caches'
      #- '{{docker_files_path}}/mysql/data/db'
      #- '{{docker_files_path}}/mysql/data/log'
      #- '{{docker_files_path}}/elasticsearch/data'
      #- '{{docker_files_path}}/redis/data'

   - name: Fix config files permission
     file:
       path: '{{item}}'
       mode: 'u=rw,g=r,o=r' #0644
     with_items:
      - '{{docker_files_path}}/rabbitmq/config/enabled_plugins'
      - '{{docker_files_path}}/rabbitmq/config/rabbitmq.conf'
     when: "docker_rabbitmq_image is defined"

   - name: "Add alias for docker container"
     lineinfile:
       path: ~/.bashrc
       line: '{{item}}'
     with_items: "{{path_aliases | default([])}}"

   - name: "Export ENV variable"
     lineinfile:
       path: ~/.bashrc
       line: '{{item}}'
     with_items: "{{export_env | default([])}}"
...