---

ansible_connection: local
ansible_become_user: root
ansible_user: araz
ansible_become_method: sudo

system_hostname: 'araz-system'

timezone: 'Asia/Tehran'

application_working_path: '/home/{{ansible_user}}/application'
docker_files_path: '{{application_working_path}}/docker'

php_project_path: /home/{{ansible_user}}/projects

docker_phpfpm_image: 'php:8.0-fpm-alpine3.14'
docker_phpfpm_image_build: 'phpfpm-8.0-alpine-custom'
docker_phpfpm_container: 'phpfpm'
docker_phpfpm_memory: '1GB'
docker_phpfpm_port: 9000

docker_redis_image: 'redis:6.2.5-alpine3.14'
docker_redis_container: 'redis'
docker_redis_memory: '256MB'

docker_rabbitmq_image: 'rabbitmq:3.9.5-management-alpine'
docker_rabbitmq_container: 'rabbitmq'
docker_rabbitmq_memory: '1GB'

docker_phpcli_image: 'php:8.0-cli-alpine3.14'
docker_phpcli_image_build: 'phpcli-8.0-alpine-custom'
docker_phpcli_memory: '1GB'

docker_node_image: 'node:14-alpine'
docker_node_image_build: 'node-14-alpine-custom'
docker_node_memory: '1GB'

docker_elasticsearch_image: 'elasticsearch:7.14.1'
docker_elasticsearch_container: 'elasticsearch'
docker_elasticsearch_memory: '4GB'

docker_mongodb_image: 'mongo:5.0-focal'
docker_mongodb_container: 'mongodb'
docker_mongodb_memory: '1GB'
docker_mongodb_external_port: 27018

docker_mysql_image: 'mysql:8.0.26'
docker_mysql_container: 'mysql'
docker_mysql_memory: '1GB'

docker_php_myadmin_image: 'phpmyadmin/phpmyadmin:5.1.1'
docker_php_myadmin_container: 'php-myadmin'
docker_php_myadmin_memory: '1GB'
docker_php_myadmin_external_port: 8090

docker_postgres_image: 'postgres:13.4-alpine'
docker_postgres_container: 'postgres'
docker_postgres_memory: '1GB'

docker_php_pgmyadmin_image: 'bitnami/phppgadmin:latest'
docker_php_pgmyadmin_container: 'php-pgmyadmin'
docker_php_pgmyadmin_memory: '1GB'
docker_php_pgmyadmin_external_port: 8091

docker_go_image: 'golang:1.17.1-alpine3.14'
docker_go_container: 'golang'
docker_go_memory: '1GB'

docker_nginx_image: 'nginx:1.21-alpine'
docker_nginx_container: 'nginx'
docker_nginx_container_memory: '1GB'
docker_nginx_external_port: 8080

docker_mongo_express_image: 'mongo-express:latest'
docker_mongo_express_container: 'mongo-express'
docker_mongo_express_container_memory: '500MB'
docker_mongo_express_external_port: 8081

docker_network_external: 'araz-frontend'
docker_network_internal: 'araz-internal-network'

docker_listen: "tcp://127.0.0.1:2375"
docker_user: '{{ansible_user}}'

ufw_rules:
  - { direction: 'incoming', policy: 'deny'}
  - { direction: 'outgoing', policy: 'allow'}
