---

ansible_connection: local
ansible_become_user: root
ansible_user: araz
ansible_become_method: sudo

system_hostname: 'araz-system'

timezone: 'Asia/Tehran'

application_working_path: '/home/{{ansible_user}}/application'
docker_files_path: '{{application_working_path}}/docker'

php_project_path: /home/{{ansible_user}}/projects


docker_php7cli_image: 'php:7.4-cli-alpine'
docker_php7cli_image_build: 'phpcli-7.4-alpine-custom'
docker_php7cli_memory: '1GB'

docker_php7fpm_image: 'php:7.4-fpm-alpine'
docker_php7fpm_image_build: 'phpfpm-7.4-alpine-custom'
docker_php7fpm_container: 'php7-fpm'
docker_php7fpm_memory: '1GB'
docker_php7fpm_port: 9000

docker_php8cli_image: 'php:8.0-cli-alpine'
docker_php8cli_image_build: 'phpcli-8.0-alpine-custom'
docker_php8cli_memory: '1GB'

docker_php8fpm_image: 'php:8.0-fpm-alpine'
docker_php8fpm_image_build: 'phpfpm-8.0-alpine-custom'
docker_php8fpm_container: 'php8-fpm'
docker_php8fpm_memory: '1GB'
docker_php8fpm_port: 9000

docker_php81cli_image: 'php:8.1-cli-alpine'
docker_php81cli_image_build: 'phpcli-8.1-alpine-custom'
docker_php81cli_memory: '1GB'

docker_php81fpm_image: 'php:8.1-fpm-alpine'
docker_php81fpm_image_build: 'phpfpm-8.1-alpine-custom'
docker_php81fpm_container: 'php81-fpm'
docker_php81fpm_memory: '1GB'
docker_php81fpm_port: 9000

docker_redis_image: 'redis:6.2.6-alpine'
docker_redis_container: 'redis'
docker_redis_memory: '256MB'

docker_rabbitmq_image: 'rabbitmq:3.9.13-management-alpine'
docker_rabbitmq_container: 'rabbitmq'
docker_rabbitmq_memory: '1GB'

docker_node_image: 'node:16-alpine'
docker_node_image_build: 'node-16-alpine-custom'
docker_node_memory: '1GB'

docker_elasticsearch_image: 'elasticsearch:7.17.0'
docker_elasticsearch_container: 'elasticsearch'
docker_elasticsearch_memory: '4GB'

docker_mongodb_image: 'mongo:5.0-focal'
docker_mongodb_container: 'mongodb'
docker_mongodb_memory: '1GB'
docker_mongodb_external_port: 27018

docker_mysql_image: 'mysql:8.0.28'
docker_mysql_container: 'mysql'
docker_mysql_memory: '1GB'

docker_php_myadmin_image: 'phpmyadmin/phpmyadmin:5.1.1'
docker_php_myadmin_container: 'php-myadmin'
docker_php_myadmin_memory: '1GB'
docker_php_myadmin_external_port: 8090

docker_postgres_image: 'postgres:13.6-alpine'
docker_postgres_container: 'postgres'
docker_postgres_memory: '1GB'

docker_php_pgmyadmin_image: 'bitnami/phppgadmin:latest'
docker_php_pgmyadmin_container: 'php-pgmyadmin'
docker_php_pgmyadmin_memory: '1GB'
docker_php_pgmyadmin_external_port: 8091

docker_go_image: 'golang:1.17.7-alpine'
docker_go_image_build: 'golang-1.17.7-alpine-custom'
docker_go_container: 'golang'
docker_go_memory: '1GB'

docker_nginx_image: 'nginx:1.21-alpine'
docker_nginx_container: 'nginx'
docker_nginx_container_memory: '1GB'
docker_nginx_external_port: 8080

docker_mongo_express_image: 'mongo-express:latest'
docker_mongo_express_container: 'mongo-express'
docker_mongo_express_container_memory: '500MB'
docker_mongo_express_external_port: 8081

docker_network_external: 'araz-frontend'
docker_network_internal: 'araz-internal-network'

docker_listen: "tcp://127.0.0.1:2375"
docker_user: '{{ansible_user}}'

ufw_rules:
  - { direction: 'incoming', policy: 'deny'}
  - { direction: 'outgoing', policy: 'allow'}

available_applications:
  - elasticsearch
  - go
  - mongodb
  - mongo-express
  - mysql
  - nginx
  - node
  - php7-cli
  - php7-fpm
  - php8-cli
  - php8-fpm
  - php81-cli
  - php81-fpm
  - php-myadmin
  - php-pgmyadmin
  - postgres
  - rabbitmq
  - redis
  
bashrc:
  - "alias php8='{{docker_files_path}}/php8-cli/cli.sh'"
  - "alias php81='{{docker_files_path}}/php81-cli/cli.sh'"
  - "alias php7='{{docker_files_path}}/php7-cli/cli.sh'"
  - "alias composer7='{{docker_files_path}}/php7-cli/composer.sh'"
  - "alias composer8='{{docker_files_path}}/php8-cli/composer.sh'"
  - "alias composer81='{{docker_files_path}}/php81-cli/composer.sh'"
  - "alias node='{{docker_files_path}}/node/node.sh'"
  - "alias mongo='{{docker_files_path}}/mongodb/mongodb.sh'"
  - "alias redis='{{docker_files_path}}/redis/redis.sh'"
  - "alias nginx='{{docker_files_path}}/nginx/nginx.sh'"
  - "alias mysql='{{docker_files_path}}/mysql/mysql.sh'"
  - "alias rabbitmq='{{docker_files_path}}/rabbitmq/rabbitmq.sh'"
  - "alias postgres='{{docker_files_path}}/postgres/postgres.sh'"
  - "alias go='{{docker_files_path}}/go/go.sh'"
  - "export GOPATH='{{docker_files_path}}/go/gopath'"