#!/usr/bin/env ansible-playbook
---

- name: Apply security restrictions for SSH
  hosts: hardening_ssh
  become: yes
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.ssh_hardening
  vars:
    ssh_server_enabled: false
    ssh_server_hardening: false
    ssh_client_hardening: true
    ssh_client_password_login: true
    
- name: Apply security restrictions for OS
  hosts: hardening_os
  become: yes
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
  vars:
    os_desktop_enable: true
    ufw_default_input_policy: 'DROP'
    ufw_default_output_policy: 'ACCEPT'
    ufw_default_forward_policy: 'DROP'
    ufw_default_application_policy: 'SKIP'
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    
...