#!/usr/bin/env ansible-playbook
---
- name: Install needed software
  hosts: software
  become: yes
  tasks:
    - name: 'Installing...'
      apt:
        package: "{{item}}"
        state: present
      with_items:
        - vim
        - git
...